Radmiraal:
  CouchDB:
    persistence:
      backendOptions:
        databaseName: ''
        host: 'localhost'
        port: 5984
        username: ''
        password: ''
        ip: '127.0.0.1'
TYPO3:
  Flow:
    object:
      excludeClasses:
        'Doctrine.CouchDB' : ['.*']
        'doctrine.couchdbodm' : ['.*']
